os: linux
dist: trusty
language: node_js
node_js:
  - "node"
before_install:
- wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
- tar -xzf install-tl-unx.tar.gz
- cd install-tl-*
- sudo ./install-tl
- export PATH=/usr/local/texlive/2017/bin/x86_64-linux:$PATH    
- export INFOPATH=$INFOPATH:/usr/local/texlive/2017/texmf-dist/doc/info
- export MANPATH=$MANPATH:/usr/local/texlive/2017/texmf-dist/doc/man
- sudo apt install equivs --no-install-recommends
- mkdir -p /tmp/tl-equivs && cd /tmp/tl-equivs
- equivs-control texlive-local
- wget -O texlive-local http://www.tug.org/texlive/files/debian-equivs-2016-ex.txt
- equivs-build texlive-local
- sudo dpkg -i texlive-local_2016-2_all.deb
- sudo apt install -f
- sudo apt install pandoc ttf-ubuntu-font-family
script: bash ./createPdf.sh
after_success: bash ./push.sh
env:
  global:
    secure: IjSRPs+trUMZ5YXsmPPWsw9vK6WFJvWL58gXn3tp1jiWjHmCBbbX82r8vzQYvzQnqRztFkvUK0tD8eQguA0+79J2jV+78HpIABJ+Q6yNmpo5RwBZ5vtUkIlFfrdZVqTncWOQcUugDFkcIoe+lmx0G6B/mNeih/CNeRyPe4UNK7d+8UGOPagj6Gq6WWR71DnqCgMKfmOi08eMuwul+HumZGs6qTay3zVJZJTrv3haCu+3bI8EnzkM7URbFqdJ6mPQQxC7IFne75GeaRA416/DXbA8hMlwFIztOtqTwMbVRL06w+GUZScdbFlmn41XhqVvel3+URQwXiqxbsjlH2cb/9UhKKVg/947G7hh8BwoieUZwAFNf5XMYBiKESyqmbJ+VnQeHr4iZJbA88KP8ckX7He9luIs2utOH5D+19e9RzjBW1WDYSa24ksloYa5EmEztgC4XeU29f6UCPu9xdlFymTgcJTKX7utZMcepcFD92SNdKMmmEAGBECwqSXZKkPGPrQ0KtdomtiLIr0T+a3EzTbPIpVoOmepP2pfo5zf8rYfCNstrfV/SBL71DWK1x92mB1+e5Pq2i3tThcdOfSON3JANHibxfIl8tlyjtjOjfAeber7x1uEQucj1lXRO4996hapgxqVX0KgGEu0DDtv4l89ixYBLA9OHV/6stYjYYA=
